[1.11.1] 'meteor create --help' command shows --vue and --apollo
meteor/meteor pull request #11189
Opened 2020-09-28 05:40 UTC by sgmheyhey

'meteor create --help' command is not showing about --vue and --apollo. it could be confused by getting meteor skeleton info.
add help message for meteor create [--vue|--aplollo]

2020-09-28 05:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meteor/meteor?pullRequest=11189) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meteor/meteor?pullRequest=11189) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meteor/meteor?pullRequest=11189) it.</sub>

2020-09-28 11:15 UTC, filipenevola commented
Hey, thanks, please sign the CLA @sgmheyhey

2020-09-30 13:12 UTC, StorytellerCZ requested changes

2020-09-30 13:12 UTC, StorytellerCZ commented on tools/cli/help.txt
> +more complete app, use the --full option. To create a basic react-based app,
The `R` in React should be capitalized as it is a name of a package/technology.

2020-11-10 16:40 UTC, filipenevola commented
I'm closing this issue because we haven't heard anything from the original poster for a while and we can't merge PRs without a signed CLA.

2020-11-27 12:10 UTC, sgmheyhey commented
Signed the CLA. It's late.

2021-01-04 15:36 UTC, merged