Document Meteor.EnvironmentVariable
meteor/meteor pull request #11204
Opened 2020-10-08 18:43 UTC by zodern

Adds documentation for Meteor.EnvironmentVariable and Meteor.bindEnvironment.

Todo: 
- [ ] Document that they can be used on the client, along with the differences

2020-10-09 07:56 UTC, StorytellerCZ requested changes

2020-10-09 07:56 UTC, StorytellerCZ commented on packages/meteor/dynamics_nodejs.js
> + * @locus server
Shouldn't the locus here be `everywhere`?

2021-05-30 18:59 UTC, StorytellerCZ commented
@zodern, do you think we can get this in for 2.3 release?

2021-06-11 18:09 UTC, filipenevola commented
Hey @zodern let's finish this docs PR this month? I think it's a good documentation to have.

2021-08-07 12:45 UTC, StorytellerCZ approved these changes

2021-08-11 16:15 UTC, filipenevola approved these changes

2021-08-11 18:42 UTC, merged