feat: adding pt-br translation to README
meteor/meteor pull request #11218
Opened 2020-10-24 20:42 UTC by Azzyew

I created a README.pt-br.md and linked it on the original README.md

I really believe we should share the knowledge the best way we can.

2020-10-24 20:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meteor/meteor?pullRequest=11218) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meteor/meteor?pullRequest=11218) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meteor/meteor?pullRequest=11218) it.</sub>

2020-10-26 09:40 UTC, StorytellerCZ commented
If we go with translating, then we should probably adopt some framework for this so it is easy to get other languages in without having crazy amount of files in the repo.

2020-10-29 18:12 UTC, filipenevola commented
Hi @Azzyew, thank you for your translation.

I'm Brazilian so I'm biased here to make a decision about this specific translation hehe.

But what people are doing to have READMEs in many languages? I'm really not aware if we have a solution for this.

Maybe we could have a folder called `translations` and then inside this folder we can replicate the same structure for each language and ask the community to fill those in. Then in the main Readme we could just add Country flags for these folders.

What do you think?

For example:
```
- translations/pt-br/
  - README.md
  - CONTRIBUTING.md
  - DEVELOPMENT.MD
  - ...
- translations/en-us/
  - README.md
  - ...
```

2020-10-29 18:44 UTC, Azzyew commented
@filipenevola that's a great idea! I'm gonna make those changes and commit when they're ready

2020-10-29 23:55 UTC, namenotrequired commented
Great initiative.

We need to be careful. Translations tend to get out of date.

We have enough contributors who speak pt-BR (like me). We just may need some minimal structure to make it more likely that future updates to the original files will be translated.

2020-10-30 02:24 UTC, Azzyew commented
translations folder created!

2020-11-11 21:19 UTC, filipenevola requested changes
I like the idea but the translation has some issues. Please check my comments.

2020-11-11 21:19 UTC, filipenevola commented on translations/PT-BR/README.pt-br.md
> +Sem ser pelo pequeno script launcher shell, o Meteor se instala dentro de seu diretório principal. Para desinstalar Meteor, use:
It seems like a literal translation `pequeno script launcher`

2020-11-11 21:19 UTC, filipenevola commented on translations/PT-BR/README.pt-br.md
> +* que manda dados pelo wire, ao invés de HTML
Wire was not translated here

2020-11-11 21:19 UTC, filipenevola commented on translations/PT-BR/README.pt-br.md
> +Depois, leia a [guia](https://guide.meteor.com) e a [documentação](https://docs.meteor.com/).
It should be "o" guia

2021-01-19 15:03 UTC, filipenevola commented
I'm really afraid that these translations would be not updated.

2021-02-25 20:27 UTC, filipenevola commented
Hi, as we are not having many discussions around this PR I'm closing it.

Of course, if we have new ideas we can re-open it. No problem.

2021-02-25 20:27 UTC, closed without merging