Catch broken symlinks in isobuild #11241
meteor/meteor pull request #11244
Opened 2020-11-13 04:09 UTC by tchiers

Change isWithinProdPackage() in isobuild/bundler.js to check for broken symlinks and throw a useful error. Fixes #11241.

2020-11-13 04:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meteor/meteor?pullRequest=11244) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meteor/meteor?pullRequest=11244) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meteor/meteor?pullRequest=11244) it.</sub>

2020-11-14 09:26 UTC, StorytellerCZ approved these changes

2020-12-09 14:13 UTC, filipenevola approved these changes

2020-12-09 14:14 UTC, filipenevola requested changes
Great, could you just update the code to avoid if/elses?

2020-12-09 14:14 UTC, filipenevola commented on tools/isobuild/bundler.js
> +          if (realpath) {
I would change this to 
```suggestion
          if (!realpath) {
              throw new Error(`Broken symbolic link encountered at ${path}`);
          }
          return isWithinProdPackage(realpath);
```

so we avoid if/else and also handle the problematic case first.

2020-12-09 20:41 UTC, filipenevola approved these changes

2020-12-09 20:42 UTC, filipenevola commented
Thanks @tchiers, as your changes are in the meteor tool they will be available in the next version of Meteor.

2020-12-09 20:42 UTC, merged