refactor: lazy import for markdown package
meteor/meteor pull request #11443
Opened 2021-05-21 14:20 UTC by jirikrepl

this is breaking change but it saves 9kb in the initial bundle

markdown pacakge is using lazy imports and will not be added to the initial bundle.

to use `{{#markdown}}...{{/markdown}}` import it first with:

`import 'meteor/markdown';`

2021-05-21 14:28 UTC, StorytellerCZ commented
@jirikrepl Thanks! While at it, can you also bump `templating` to `1.4.0` in `package.js` while you are at it? If you want you can also update the readme with how to use it, but do please note that this package is deprecated.

2021-05-21 14:59 UTC, jirikrepl commented
Thanks! In the readme.md of this package I put a link to these docs https://docs.meteor.com/packages/markdown.html

And I am proposing this change in the docs, which explain this change
https://github.com/meteor/docs/pull/722

2021-05-21 14:59 UTC, StorytellerCZ requested changes

2021-05-21 14:59 UTC, StorytellerCZ commented on packages/deprecated/markdown/README.md
> +[Source code of released version](https://github.com/jirikrepl/meteor/tree/master/packages/deprecated/markdown) | [Source code of development version](https://github.com/jirikrepl/meteor/tree/devel/p
This should point to `meteor`, not your personal repo.

2021-05-21 15:02 UTC, jirikrepl commented
ok, thanks. I fixed it

2021-05-21 15:26 UTC, StorytellerCZ approved these changes

2021-05-24 11:36 UTC, StorytellerCZ commented
Given this change let's make a major version bump for 2.3 release and then move it to the Blaze repository where this package belongs.

2021-05-24 14:49 UTC, merged