Async publications unit testing
meteor/meteor pull request #11588
Opened 2021-08-17 19:40 UTC by renanccastro

This PR adds unit testing for the new feature developed here: https://github.com/meteor/meteor/pull/11444

2021-08-18 09:23 UTC, StorytellerCZ approved these changes

2021-08-18 22:12 UTC, filipenevola requested changes
See my inline comment and also I believe it's missing a test for error handling. 

It would be nice to be sure the error is handled correctly when thrown from within an asynchronous function.

2021-08-18 22:12 UTC, filipenevola commented on packages/ddp-server/livedata_server_async_tests.js
> +    await sleep(50)
; is missing

2021-08-20 01:39 UTC, filipenevola approved these changes

2021-08-20 01:39 UTC, merged