NPM installer should also work with linux/mac
meteor/meteor pull request #11590
Opened 2021-08-18 17:11 UTC by renanccastro

In this PR I change a little the way we were doing before, which was using NPM to link the binary in a "path" included directory.
This won't work for multiplatform, because package.json only allows us to specify one possible file for the bin key.

The strategy is discovering which system we are doing the install, and adding .meteor to the execution PATH, windows included.

2021-08-18 22:02 UTC, filipenevola requested changes
See my recommendations.

2021-08-18 22:02 UTC, filipenevola commented on npm-packages/meteor-installer/install.js
> +  if(os.platform() === 'darwin' || os.platform() === 'linux') {
same from above.

```js
if (isWindows) {
  child_process.execSync(`setx path "${meteorPath}/;%path%`);
  return;
}

// non-windows code

2021-08-18 22:02 UTC, filipenevola commented on npm-packages/meteor-installer/install.js
> +  const downloadPlatform = {
this is a constant (should be UPPER_CASE) and could be declared in the file scope.

2021-08-18 22:04 UTC, filipenevola commented
@renanccastro I've got this error on MacOS Intel.

```
npm install -g meteor
/Users/filipe/.nvm/versions/node/v12.14.0/bin/meteor -> /Users/filipe/.nvm/versions/node/v12.14.0/lib/node_modules/meteor/meteor.bat
/Users/filipe/.nvm/versions/node/v12.14.0/bin/meteor-installer -> /Users/filipe/.nvm/versions/node/v12.14.0/lib/node_modules/meteor/cli.js

> meteor@2.3.4 install /Users/filipe/.nvm/versions/node/v12.14.0/lib/node_modules/meteor
> node cli.js install

/Users/filipe/.nvm/versions/node/v12.14.0/lib/node_modules/meteor/config.js:8
  throw new Error('LOCALAPPDATA env var is not set.');
  ^

Error: LOCALAPPDATA env var is not set.
    at Object.<anonymous> (/Users/filipe/.nvm/versions/node/v12.14.0/lib/node_modules/meteor/config.js:8:9)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/filipe/.nvm/versions/node/v12.14.0/lib/node_modules/meteor/install.js:9:59)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor@2.3.4 install: `node cli.js install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/filipe/.npm/_logs/2021-08-18T22_03_18_761Z-debug.log

```

2021-08-18 22:07 UTC, filipenevola commented
It seems to be working on MacOS Intel:

```
 meteor-installer git:(feature/installer-linux) ✗ npm link   

> meteor@2.3.5 install /Users/filipe/Documents/meteor/ws/meteor/npm-packages/meteor-installer
> node cli.js install

=> Meteor Downloaded in 27.444s
=> Extracting the tarball, this may take some time
=> Meteor extracted in 25.45s

***************************************

Meteor has been installed!

*You might need to open a new terminal windows to have access to the meteor command.*

To get started fast:

  $ meteor create ~/my_cool_app
  $ cd ~/my_cool_app
  $ meteor

Or see the docs at:

  docs.meteor.com

Deploy and host your app with Cloud:

  www.meteor.com/cloud

***************************************
  
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN meteor@2.3.5 No repository field.

audited 45 packages in 53.304s

2 packages are looking for funding
  run `npm fund` for details

found 2 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
/Users/filipe/.nvm/versions/node/v12.14.0/bin/meteor-installer -> /Users/filipe/.nvm/versions/node/v12.14.0/lib/node_modules/meteor/cli.js
/Users/filipe/.nvm/versions/node/v12.14.0/lib/node_modules/meteor -> /Users/filipe/Documents/meteor/ws/meteor/npm-packages/meteor-installer
```

2021-08-19 13:08 UTC, StorytellerCZ commented
On Ubuntu had to go with `sudo` and then still got an error:
```bash
npm ERR! code 1
npm ERR! path /home/storyteller/Web/meteor/meteor/npm-packages/meteor-installer
npm ERR! command failed
npm ERR! command sh -c node cli.js install
npm ERR! => Meteor Downloaded in 41.87s
npm ERR! internal/fs/utils.js:314
npm ERR!     throw err;
npm ERR!     ^
npm ERR! 
npm ERR! Error: EACCES: permission denied, open '/root/.meteor-install-started.txt'
npm ERR!     at Object.openSync (fs.js:498:3)
npm ERR!     at Object.writeFileSync (fs.js:1524:35)
npm ERR!     at b.<anonymous> (/home/storyteller/Web/meteor/meteor/npm-packages/meteor-installer/install.js:102:10)
npm ERR!     at b.emit (events.js:400:28)
npm ERR!     at WriteStream.<anonymous> (/home/storyteller/Web/meteor/meteor/npm-packages/meteor-installer/node_modules/node-downloader-helper/dist/index.js:1:9313)
npm ERR!     at WriteStream.emit (events.js:400:28)
npm ERR!     at emitCloseNT (internal/streams/destroy.js:87:10)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:81:21) {
npm ERR!   errno: -13,
npm ERR!   syscall: 'open',
npm ERR!   code: 'EACCES',
npm ERR!   path: '/root/.meteor-install-started.txt'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-19T13_04_22_707Z-debug.log
```

BUT it seemed to install and work just fine.

2021-08-19 13:52 UTC, renanccastro commented
@StorytellerCZ why you needed sudo? Sudo shouldn't be needed.

2021-08-19 14:22 UTC, StorytellerCZ commented
In my case anything global related has to be started with `sudo`, otherwise I get `EACCES` error.

2021-08-19 18:44 UTC, renanccastro commented
Got it, on Ubuntu it's common to install nodejs with apt, which in turn will make the global node_modules chowned by root.
I could repro it, and we will need to inform that in these cases if they are running with sudo, they have to pass --unsafe-perm to npm install -g meteor, otherwise, npm won't let the install script run.

Other than that, when running with sudo, the permission of the .meteor folder is wrong, I will also fix it.

2021-08-20 01:50 UTC, filipenevola approved these changes

2021-08-24 14:17 UTC, StorytellerCZ approved these changes

2021-08-30 13:29 UTC, ixdi commented
When using npm installer on Linux an error appears:
```
LOCALAPPDATA env var is not set
```
I thought this env was only for Windows users...

2021-08-30 13:30 UTC, renanccastro commented
Hello @ixdi . Currently we only support linux/mac in the beta channel of the installer: meteor@2.3.6-beta6.

We will release in the main channel this week.

2021-08-30 13:37 UTC, ixdi commented
Thank you @renanccastro for the reply
I was using beta 1 and not beta 6. 
The error continues...
![Captura de pantalla de 2021-08-30 15-34-43](https://user-images.githubusercontent.com/3193539/131347797-49c46e42-cf47-4aaa-8cd2-782724e5393a.png)

2021-08-30 13:39 UTC, renanccastro commented
@ixdi in your screenshot seems like the npm install command worked, and the update command failed. NPM is trying to update the package to the main channel, not the beta one. This doesn't seem like an issue with the installer.

2021-08-30 19:56 UTC, merged