use callback-hook package
meteor/meteor pull request #11615
Opened 2021-09-01 16:51 UTC by brucejo75

In response to https://github.com/meteor/meteor/pull/11607#issuecomment-907904575

For the 2 callbacks I introduced I have updated to use the meteor `callback-hook` package.

2021-09-01 16:53 UTC, brucejo75 commented
Working on the History.md now.

2021-09-01 17:40 UTC, StorytellerCZ requested changes

2021-09-01 17:40 UTC, StorytellerCZ commented on packages/webapp/webapp_server.js
> +  runtimeConfig.updateHooks.each((cb) => {
You can use here `forEach`, it has been added in `callback-hook@1.4.0` which is available on the release branch.

2021-09-01 19:07 UTC, brucejo75 commented
@StorytellerCZ, I am working on the api box stuff.  If you can give me another day, I will fold it into this PR (need to add into the code).

2021-09-01 20:32 UTC, StorytellerCZ approved these changes

2021-09-02 01:09 UTC, filipenevola commented
@brucejo75 last changes like this are dangerous, make sure you test these changes properly 😉

2021-09-03 21:16 UTC, brucejo75 commented
@StorytellerCZ, @filipenevola,

I have documented the new methods in `WebApp` via jsdoc & `apibox`.  While I was at it I moved `connectHandlers` documentation to `apibox` as well.

**Note**: this documentation depends on https://github.com/meteor/docs/pull/753 & uses a new tag `@isprototype` to suppress the `importName` & `filepath` from the `api-heading` when documenting callback functions.

2021-09-06 09:48 UTC, merged