installer: Add a flag to skip modifying exec path
meteor/meteor pull request #11777
Opened 2021-11-21 19:30 UTC by ebroder

The Meteor installer currently modifies the dotfiles of the user running it unconditionally. This makes sense as default behavior, but isn't always optimal. (For instance, I setup my dotfiles before installing meteor, and those dotfiles have the PATH modification already).

This change adds a flag to disable that behavior. I opted for an npm-managed argument, since that felt the most fluid of an interface to me. It's also accessible through a handful of means - you can use `npm install -g meteor --no-meteor-setup-exec-path`, but you can also pass it through the environment (`npm_config_meteor_setup_exec_path=false npm install -g meteor`). I used [this post](https://kgrz.io/how-npm-install-passes-cli-args.html) as a reference on how these arguments work, although the behavior of environment variables has changed a bit since that was written.

I didn't add any documentation yet. I assume that we'll want some, but I'm not sure where to put it, so pointers would be appreciated. (Easiest would probably be stuffing it in the installer README?)

I did run a handful of tests to make sure this worked the way I thought it did. First, here's a standard install:

```
evan@mathias meteor-installer (installer-optional-setup-path) % npm run-script -g install

> meteor@2.5.1 install
> node cli.js install
[...]
evan@mathias meteor-installer (installer-optional-setup-path) % tail -n 1 ~/.zshrc
export PATH=/Users/evan/.meteor:$PATH
```

Here's passing the argument through argv:

```
evan@mathias meteor-installer (installer-optional-setup-path) % npm run-script -g install --no-meteor-setup-exec-path

> meteor@2.5.1 install
> node cli.js install
[...]
evan@mathias meteor-installer (installer-optional-setup-path) % tail -n 1 ~/.zshrc
autoload -Uz compinit && compinit
```

And here's passing it through an environment variable (note that `--no-blah` in arguments gets canonicalized to `blah=''` in the env):

```
evan@mathias meteor-installer (installer-optional-setup-path) % npm_config_meteor_setup_exec_path=false npm run-script -g install

> meteor@2.5.1 install
> node cli.js install
[...]
evan@mathias meteor-installer (installer-optional-setup-path) % tail -n 1 ~/.zshrc
autoload -Uz compinit && compinit
```

2021-11-21 19:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meteor/meteor?pullRequest=11777) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meteor/meteor?pullRequest=11777) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meteor/meteor?pullRequest=11777) it.</sub>

2021-12-11 21:44 UTC, ebroder commented
Hey folks - any chance of getting some eyes on this?

2021-12-14 12:14 UTC, renanccastro requested changes
There are 2 points where I think this should be documented:
- https://docs.meteor.com/install.html#installation
- and the readme as you said

I think this is a good addition, but as it is not the default behavior, a flag with a "ignore" word is better for it!

Sorry for the delay here.

2021-12-14 12:14 UTC, renanccastro commented on npm-packages/meteor-installer/config.js
> +  if (!Object.prototype.hasOwnProperty.call(process.env, 'npm_config_meteor_setup_exec_path')) {
This flag is better as an opt-out of the default behavior, something like:

`--ignore-meteor-setup-exec-path`

So this code here could be simplified to 

`return process.env.npm_ignore_meteor_setup_exec_path`

2021-12-14 17:44 UTC, ebroder commented
Sure, that works for me. I've pushed an update that switches to that flag name and updates the documentation files you suggested.

2021-12-14 21:08 UTC, zodern commented
Would it be possible to make this automatic? It seems Meteor could detect when the PATH is already correct and then do nothing.

2021-12-14 21:29 UTC, ebroder commented
I'm not wild about that, personally. We could certainly inspect `$PATH` in the current process and check for Meteor, but that wouldn't actually tell us anything about what's in the user's dotfiles, and dotfiles themselves can be complicated enough that I wouldn't want to try and check them to see if the config is already there.

2022-02-02 05:14 UTC, ebroder commented
Hey folks - what can I do to move this forward?

2022-02-02 11:37 UTC, renanccastro approved these changes

2022-02-02 11:38 UTC, renanccastro commented
Sorry for the delay @ebroder
This PR will be released in 2.6.1, which should be early this month!

Thanks for your contribution.

2022-02-02 11:40 UTC, merged