Update decimal.js
meteor/meteor pull request #11875
Opened 2022-01-28 01:05 UTC by harryadel

Might be nice to add it along #11867

2022-02-03 18:56 UTC, denihs requested changes

2022-02-03 18:56 UTC, denihs commented on packages/non-core/mongo-decimal/package.js
> +  "decimal.js": "10.3.1"
Hi @harryadel, sorry, but I didn't understand the purpose of bumping the version of this package without making any actual change to it. Could you explain it to me?

2022-02-03 21:50 UTC, harryadel commented
:thinking:

2022-02-08 20:29 UTC, filipenevola commented
@harryadel what are the improvements and changes in this minor version update?

We will be more strict with PRs to follow our guideline for contribution. https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#proposing-your-change

2022-02-09 00:54 UTC, harryadel commented
@filipenevola I guess my argument would be the same as one [here](https://github.com/meteor/meteor/pull/11837#issuecomment-1033214636)

2022-02-10 18:10 UTC, denihs approved these changes

2022-02-10 18:11 UTC, merged