Allow setting a custom ddp-rate-limit message per rule
meteor/meteor pull request #12082
Opened 2022-07-12 04:39 UTC by wreiske

Added new DDPRateLimiter.setErrorMessageOnRule function that allows developers to specify custom error messages for each rule instead of being limited to one global error message for every rule.

## Example with function
```
const setupGoogleAuthenticatorRule = {
  userId(userId) {
    const user = Meteor.users.findOne(userId);
    return user;
  },
  type: 'method',
  name: 'Users.setupGoogleAuthenticator',
};

// Add the rule, allowing up to 1 google auth setup message every 60 seconds
const ruleId = DDPRateLimiter.addRule(setupGoogleAuthenticatorRule, 1, 60000);
DDPRateLimiter.setErrorMessageOnRule(ruleId, function (data) {
  return `You have reached the maximum number of Google Authenticator attempts. Please try again in ${Math.ceil(data.timeToReset / 1000)} seconds.`;
});
```

![chrome_RexK4LUU2C](https://user-images.githubusercontent.com/6295044/178409416-5ea3254d-e74a-4ab9-8166-ff1b0d2355af.png)

## Example with string
```
// Add the rule, allowing up to 1 google auth setup message every 60 seconds
const ruleId = DDPRateLimiter.addRule(setupGoogleAuthenticatorRule, 1, 60000);
DDPRateLimiter.setErrorMessageOnRule(ruleId, 'Example as a single string error message');
```
![image](https://user-images.githubusercontent.com/6295044/178409699-50e9540c-2a2d-45ef-a3aa-9f15faabfa05.png)

2022-07-12 06:20 UTC, afrokick commented on packages/ddp-rate-limiter/ddp-rate-limiter.js
> +const errorMessageByRule = [];
`{}` or `Map` more suitable than `[]` for key-value

2022-08-20 23:40 UTC, wreiske commented
@StorytellerCZ , thought on this PR? Would love your review / feedback. Thanks!

2023-03-24 07:40 UTC, StorytellerCZ requested changes
The packages should have feature bump and we need a changelog entry, other than that LGTM.

2023-03-27 20:25 UTC, wreiske commented
> The packages should have feature bump and we need a changelog entry, other than that LGTM.

@StorytellerCZ , would you like for me to do this? Let me know and I can dive in....

2023-04-04 13:26 UTC, merged