Change Accounts and Oauth to use Async methods.
meteor/meteor pull request #12156
Opened 2022-08-23 00:29 UTC by edimarlnx

Change Accounts and Oauth to use Async methods.

[Work in Progress]

In this PR, we are starting changes to remove dependencies of Fibers in packages related to Accounts and OAuth. 

In this phase, we will change all codes that depend on Fibers to work synchronously to async methods. 
For example: When waiting for HTTP requests, methods with Meteor.wrapAsync, etc.

- [ ] Change google oauth
- [ ] Change facebook oauth

..
TODO: Include all affected packages in the check list.

2022-08-27 22:45 UTC, radekmie reviewed
It's important to document that a few accessible functions (e.g., `Accounts._checkPassword`) are now `async`. I use it in my projects, and I don't think that's uncommon.

Similarly, a guide on how to migrate custom `loginWithX` packages is crucial here (even if it'd say "it'll just work").

2022-08-28 00:13 UTC, zodern commented
I think https://github.com/meteor/meteor/issues/10672 will need to be fixed since there will probably be problems if some of these methods are not blocking, especially the login and logout methods.

2022-09-20 13:59 UTC, edimarlnx commented
> It's important to document that a few accessible functions (e.g., `Accounts._checkPassword`) are now `async`. I use it in my projects, and I don't think that's uncommon.
I changed it to preserve compatibility mode. 


> Similarly, a guide on how to migrate custom `loginWithX` packages is crucial here (even if it'd say "it'll just work").
I will see it.

Thank you!

2022-09-21 15:25 UTC, StorytellerCZ requested changes

2022-09-21 15:25 UTC, StorytellerCZ commented on packages/facebook-oauth/facebook_server.js
> +import {Accounts} from 'meteor/accounts-base';
This seems to be some linting happening here. I don't think this is the correct one.

2022-10-24 18:32 UTC, merged

2022-11-07 22:13 UTC, perbergland commented
There are a bunch of sync mongodb updates left in accounts_server.js (`users.update(...)`), esp for the token handling method like _insertHashedLoginToken (an example of a method we use in our code to implement SSO login).

All these methods need to become async too and use the mongo async methods, preferrably using the established pattern of adding an async version for now. Is that also planned for 2.9 or is that work saved for a 2.9.x release?

2022-12-05 14:05 UTC, Grubba27 commented on packages/google-oauth/google_server.js
> +  console.log({ request });
Shouldn't this be removed?

2022-12-05 14:06 UTC, Grubba27 commented on packages/google-oauth/google_server.js
> +  console.log({ result });
And this one