Core packages types 2
meteor/meteor pull request #12175
Opened 2022-09-09 13:27 UTC by piotrpospiech

The rest of the type definitions for core packages. Created as a draft until [previous PR ](https://github.com/meteor/meteor/pull/12174)is tested. It can be reviewed though.

2022-11-03 18:17 UTC, radekmie approved these changes

2022-11-03 20:48 UTC, StorytellerCZ requested changes

2022-11-03 20:48 UTC, StorytellerCZ commented on packages/accounts-base/package-types.json
> +  "typesEntry": "__types/accounts-base.d.ts"
This does not look like the correct path.

2022-11-04 12:32 UTC, Grubba27 commented on packages/accounts-base/package-types.json
> +  "typesEntry": "__types/accounts-base.d.ts"
```suggestion
  "typesEntry": "accounts-base.d.ts"
```

2022-11-04 12:35 UTC, merged