chore: Add Viewport tags to all skeletons to fix mobile look
meteor/meteor pull request #12624
Opened 2023-05-07 15:29 UTC by fredmaiaarantes

To optimize the mobile viewing experience, it's recommended to add viewport tags to our apps.

This simple fix, adds them to all our skeletons and can ensure that the content on the website appears properly on different mobile devices, regardless of their screen size or orientation. After this is released, we can also remove [one step](https://react-tutorial.meteor.com/simple-todos/01-creating-app.html#1-6-Mobile-look) from our tutorials, making it easier to create new Meteor apps.

2023-05-07 16:36 UTC, StorytellerCZ approved these changes

2023-05-08 04:08 UTC, zodern requested changes
Having viewport tags in new apps will be nice. I'm surprised Meteor didn't already do this.

2023-05-16 10:55 UTC, fredmaiaarantes commented on tools/static-assets/skel-apollo/client/main.html
> +  <meta charset="utf-8"/>
Thanks, I removed it.

2023-05-16 10:56 UTC, fredmaiaarantes commented on tools/static-assets/skel-apollo/client/main.html
> +      content="width=device-width, height=device-height, viewport-fit=cover, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
Tks, I'm switching to having simpler tags as recommended by W3Schools.
https://www.w3schools.com/css/css_rwd_viewport.asp

2023-05-16 10:56 UTC, fredmaiaarantes commented on tools/static-assets/skel-apollo/client/main.html
> +  <meta name="apple-mobile-web-app-capable" content="yes"/>
Tks, I'm switching to having simpler tags as recommended by W3Schools.
https://www.w3schools.com/css/css_rwd_viewport.asp

2023-05-16 11:19 UTC, closed without merging