Add a new publication strategy
meteor/meteor pull request #12742
Opened 2023-08-17 14:32 UTC by alisnic

We have an application that publishes *a lot* of documents, from which only a small subset of documents is updated. We now have a few very heavy users which cause strain on our containers due to server merge box logic.

While in theory NO_MERGE solves or problem, our e2e suite is failing because NO_MERGE does not track document use across multiple publication from the same collection.

This PR is an attempt to solve the limitations of NO_MERGE, while keeping most of its the memory and CPU benefits.

This change was tested in a e2e suite with 725 test examples.

2023-08-18 06:58 UTC, StorytellerCZ requested changes

2023-08-18 06:58 UTC, StorytellerCZ commented on packages/ddp-server/livedata_server.js
> +  // NO_MERGE_MULTE is similar to NO_MERGE, but it does track whether a document
Typo here

2023-08-18 06:58 UTC, StorytellerCZ commented on packages/ddp-server/livedata_server.js
> +_.extend(DummyDocumentView.prototype, {
Use `Object.assign()` instead.

2023-08-18 10:06 UTC, StorytellerCZ approved these changes
Looks good so far, but would also appreciate an entry to the docs.

2023-08-18 10:53 UTC, alisnic commented
> Looks good so far, but would also appreciate an entry to the docs.

Sure thing! I wasn't sure the change would be accepted that's why I didn't include any changes to documentation.

Is changing `docs/pubsub.md` enough, or should I update the changelog as well?

2023-09-25 13:38 UTC, StorytellerCZ approved these changes

2023-10-17 11:43 UTC, merged

2023-10-31 09:30 UTC, dd137 commented
(Hi there. There was a small omission in the `pubsub.md` update: "There are ~three~ **four** publications strategies:")

2023-10-31 10:29 UTC, StorytellerCZ commented
Fixed