Subscribe stop crash
meteor/meteor pull request #13034
Opened 2024-02-26 19:48 UTC by perbergland

Fixes #13028 and adds validation to catch more errors.

I suspect there are plenty more missing awaits, but at least these a few are fixed here.
Also turned var's into const's because it needs to be done some day.

I tried to preserve the sequence of calls between the constructor and the async _init method

2024-03-05 14:18 UTC, denihs commented
Hi, @perbergland. Some tests are failing, but maybe it is just a matter of rerunning them.

Could you merge the release-3.0 branch here again? 

Let's see if the tests are going to pass.

I tried to merge release-3.0 here, but I cannot commit to your fork.

2024-03-06 15:05 UTC, denihs requested changes

2024-03-06 15:55 UTC, perbergland commented on packages/mongo/polling_observe_driver.js
> +      self._cursorDescription, function (notification) {
Thx will fix

2024-03-06 19:43 UTC, perbergland commented on packages/mongo/polling_observe_driver.js
> +      self._cursorDescription, function (notification) {
I can’t see what tests broke on circle-ci? Can I run them locally? In any case, the code is probably fixed now

2024-03-07 12:51 UTC, Grubba27 approved these changes
LGTM.

The failing test in the CI is expected(docs issue).

2024-03-12 20:55 UTC, denihs commented on packages/mongo/polling_observe_driver.js
> +      self._cursorDescription, function (notification) {
Yeap, to run locally, you can execute ` ./meteor test-packages `. But they're all passing now and look good to me! Great job!

2024-03-12 20:55 UTC, denihs approved these changes

2024-03-12 20:56 UTC, merged