Issue #13121  updated the error handling within the Meteor method for…
meteor/meteor pull request #13124
Opened 2024-05-04 17:55 UTC by Sageyuva

… inserting data into a MongoDB collection

2024-05-04 17:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meteor/meteor?pullRequest=13124) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meteor/meteor?pullRequest=13124) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meteor/meteor?pullRequest=13124) it.</sub>

2024-05-04 22:04 UTC, StorytellerCZ requested changes

2024-05-04 22:04 UTC, StorytellerCZ commented on packages/allow-deny/allow-deny.js
> +        throw new Meteor.Error(409, `Duplicate key error on index: ${indexName}`);
Please format this properly. Running this through a linter should fix this automatically.

2024-05-04 22:05 UTC, StorytellerCZ commented
Hello @Sageyuva before we proceed further please sign the CLA as per the link in the automated comment above. Thank you!

2024-05-19 13:49 UTC, StorytellerCZ commented
Hi @Sageyuva please sign the CLA or we will have to reject your PR.

2024-06-13 07:57 UTC, StorytellerCZ commented
Given that the CLA has not been signed we will have to close this PR. @Sageyuva please sign the CLA so that we can consider this PR. I will close this in few days if the situation doesn't change.

2025-12-11 18:20 UTC, italojs requested changes

2025-12-11 18:20 UTC, italojs commented on packages/allow-deny/allow-deny.js
> -            throw new Meteor.Error(409, e.toString());
btw the error message can easily change in the next mongo versions

2026-08-31 21:18 UTC, Grubba27 commented
CLA has not been signed

2026-08-31 21:18 UTC, closed without merging