Updated a link that redirects to 404 to the meteor history link
meteor/meteor pull request #13322
Opened 2024-09-01 22:18 UTC by mvorot

2024-09-01 22:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meteor/meteor?pullRequest=13322) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meteor/meteor?pullRequest=13322) before we can accept your contribution.<br/><hr/>**Mikhail Vorotnikov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meteor/meteor?pullRequest=13322) it.</sub>

2024-09-01 23:03 UTC, mvorot commented
I realize this issue didn’t have a "ready" tag, but since it’s a very minor fix, I thought it would be a good opportunity for my first open-source contribution.

2024-09-02 13:48 UTC, leonardoventurini requested changes

2024-09-02 13:48 UTC, leonardoventurini commented on tools/packaging/updater.js
> +        " is available. Check the changelog https://v3-docs.meteor.com/history.html and update this project with 'meteor update'.");
```suggestion
        " is available. Check the changelog https://docs.meteor.com/history.html and update this project with 'meteor update'.");
```

Now it's just `docs.`.

2024-09-04 14:59 UTC, denihs approved these changes

2024-09-04 15:00 UTC, denihs commented
Once the tests pass, we can merge it. Thank you!

2024-09-05 01:46 UTC, mvorot commented
@denihs Build and Test fails because my forked brach is not found in upstream origin. Do you know how to fix it?

2024-09-10 15:16 UTC, denihs commented
We are going to merge it like this. Thank you!

2024-09-10 15:16 UTC, merged