Update type definitions for accounts-base for functions that became async
meteor/meteor pull request #13364
Opened 2024-09-20 16:41 UTC by 9Morello

This is a minor PR that updates some function signatures in the `accounts-base.d.ts` file to reflect the fact that they became asynchronous. `addEmail` was renamed to `addEmailAsync`, as per the implementation.

2024-09-23 14:23 UTC, denihs requested changes

2024-09-23 14:23 UTC, denihs commented on packages/mongo/mongo_driver.js
> +[...CURSOR_METHODS, Symbol.asyncIterator].filter(method => method !== CURSOR_METHODS[0]).forEach(function(method) {
```
method !== CURSOR_METHODS[0]
```

If, in the future, we forget about these rules and add something at the top of this array, this code won't work as expected. 

It's best to use the `if` expression here.

2024-09-23 14:24 UTC, denihs commented
There are something some tests breaking. Could you check those?

2024-09-25 15:53 UTC, 9Morello commented
@denihs I made another PR which doesn't include unrelated changes https://github.com/meteor/meteor/pull/13374

2024-09-25 15:53 UTC, closed without merging