Create change.js
meteor/meteor pull request #13381
Opened 2024-10-02 13:47 UTC by Samarth981

2024-10-02 13:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meteor/meteor?pullRequest=13381) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meteor/meteor?pullRequest=13381) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meteor/meteor?pullRequest=13381) it.</sub>

2024-10-02 13:49 UTC, Samarth981 commented
Solved issued number #12610

2024-10-02 13:49 UTC, Samarth981 commented
solved issue for #12610

2024-10-02 13:50 UTC, Samarth981 commented
solve this #12610

2024-10-02 15:16 UTC, denihs commented
@Samarth981, a few things:

1. Please sign the [CLA](https://github.com/meteor/meteor/pull/13381#issuecomment-2388691709).
2. Could you include in the description an explanation of what you did and how this solved the issue?
3. Please add tests for this new code. Especially one that simulates the issue being solved by your code.

2024-10-02 17:14 UTC, Samarth981 commented
I have update my first commit please check.

2024-10-03 07:48 UTC, StorytellerCZ requested changes
The changes described and the actual code do not match. There are no new tests and no fixes. Instead only a new file is created that is not tied to anything and mostly copies existing code.

2024-10-03 07:48 UTC, StorytellerCZ commented on packages/accounts-base/change.js
> +import { UsersDB } from '../../api/collections/users/server/users';
This looks like import from a project specific file. I can't find this in the repository.

2024-10-03 18:30 UTC, denihs commented
@Samarth981 I'm closing this PR as it makes no sense.

You already opened the other two like this.

If the next PR you open follows this same path, we'll have to block you from this organization.

2024-10-03 18:30 UTC, closed without merging