Fix Cordova issue when using accounts-base
meteor/meteor pull request #13459
Opened 2024-11-13 16:13 UTC by nachocodoner

OSS-616

Context: https://github.com/meteor/meteor/issues/13450

## Issue

This PR addresses an issue that started to happen on early Meteor 3 versions and caused from [updating "core-js" packages](https://github.com/meteor/meteor/commit/79551fb53b2f48ac1f42405f2893b8f9d5553054) to the latest version. The Meteor `url` package, used by `accounts-base`, relies on `core-js` to maintain compatibility with legacy builds, which are essential for running the app in Cordova webviews. Updating `core-js` required handling breaking changes like the one here, and we currently lack regression tests to verify Cordova builds with the accounts package.

## Solution

In future reviews, we should be particularly cautious with version bumps, especially with minor or major updates, to find impacts on related packages.

To resolve the issue with newer versions, I added `url-search-params-polyfill` for legacy builds, as latest `core-js` no longer supports `URLSearchParams` and assumes it’s available, but only does for modern bundles.

2024-11-13 18:32 UTC, wreiske commented
I pulled down the changes. I haven't seen any issues so far, nevertheless I would hate to be the one that says "All Good!" and have this break everyone's apps! 

I'm going to keep testing this PR today in dev and might push the changes out to production tonight to see how tomorrow goes.

2024-11-13 22:36 UTC, wreiske commented
So far so good. I'm pushing out to production for sure tonight. I'll let you know 🙏

2024-11-14 13:16 UTC, nachocodoner commented
I've tested this myself and also commented on the original issue. It's always helpful to have another set of eyes reviewing.

Thanks so much!

2024-11-14 13:33 UTC, Grubba27 requested changes
Is there a way to add testing to this?

2024-11-14 13:36 UTC, Grubba27 approved these changes
testing this kind of regression seems hard...

2024-11-14 13:39 UTC, nachocodoner commented
Yes, I’ve used tools like [Appium](https://appium.io/docs/en/latest/) before. Setting up the infrastructure for effective testing pipelines took some time. Adding something similar could be useful, especially as we consider future native Meteor apps with Capacitor or a similar tool.

2024-11-15 02:17 UTC, wreiske commented
Ran it all day and didn't have any reports of issues. 🎉 . I guess worst caste scenario is we might have to create a hotfix and push a new `url` package out if someone does find issues.

2024-11-15 17:53 UTC, zodern commented
> To resolve the issue with newer versions, I added url-search-params-polyfill for legacy builds, as latest core-js no longer supports URLSearchParams and assumes it’s available, but only does for modern bundles.

I was surprised that core-js no longer polyfills URLSearchParams, so I looked into it. core-js does still have the polyfill, and the import Meteor is using (`core-js/proposals/url`) is one of the ways to load it. It's even the [first polyfill loaded by the import](https://github.com/zloirock/core-js/blob/a1298dcf04a231abe7ef6b0021c04cb06db8a9b2/packages/core-js/web/url.js#L2).

The polyfill's for URLSearchParams aren't that small, so it would be nice if the legacy client doesn't load two of them.

2024-11-18 15:56 UTC, nachocodoner commented
Yes, that's what I initially thought, @zodern. However, no matter what I load from `core-js`, the error still occurs. `URLSearchParams` isn't loaded at all, and other crashes happen as well when I try to load `URLSearchParams` by demand from `core-js` modules as the one you pointed and set it globally. It might be an issue with the library itself, I could report it. 
I can try again on my side to double-check, but I already tested several options with no solution. Other option to perserve one dependency is to downgrade the `core-js` package, but this is not a good long-term solution either.

As for size, I checked how much `url-search-params-polyfill` takes, and it doesn’t seem too large. https://bundlephobia.com/package/url-search-params-polyfill@8.2.5 I understand to keep the meteor core as lean as possible, but I was thinking this was required after latest `core-js` upgrades, with no option to see `URLSearchParams` available.

![image](https://github.com/user-attachments/assets/0acbd163-aa95-4db4-8bbb-83c975cabf4e)

2024-11-18 16:49 UTC, nachocodoner commented
![image](https://github.com/user-attachments/assets/1580314c-cb9e-4d31-9b93-f94d0872791a)

Just for you to check what I did. Since the error behind the upgrade is always `TypeError: undefined is not an object (evaluating '$URLSearchParams.prototype')`, I trying to load by demand the `core-js/web/url-search-params` polyfill available from `core-js`. However, it crashes the same way, since that code imports other required parts `web.url-search-params.delete.js` that uses `URLSearchParams`. I might ask for help on core-js repository itself, but this seems an issue on their end.

The only way I found to overcome this is to import an alternative `url-search-params` polyfill that overcomes the core-js limitation.

2024-11-19 14:06 UTC, nachocodoner commented
I've opened a new issue on `core-js` to investigate a possible regression: https://github.com/zloirock/core-js/issues/1380.

Regarding this PR, we will proceed with merging it to address critical issues causing crashes in Cordova apps. We've received many reports about this, and developers have already helped validate the fix. It will be available on release 3.1.

We'll revisit this in the future once we get any confirmation or a fix from `core-js`.

2024-11-19 16:22 UTC, merged

2024-11-23 03:59 UTC, zodern commented
@nachocodoner I agree with the response in the core-js issue that this is an issue in Meteor. I looked into it a little bit more, and it's a problem caused by Meteor's package scoping. It's creating a package-scoped `URLSearchParams` variable, which is still undefined by the time `core-js/modules/web.url-search-params.delete.js` runs. I don't remember if Meteor scans files in node_modules when identifying variables to add to the package scope. Assuming it doesn't, you should be able to fix this by removing the URLSearchParams pseudo global from the package code.