FIX: Add missing types to roles package
meteor/meteor pull request #13508
Opened 2024-12-06 14:15 UTC by Grubba27

it was missing an `addAssets` in the `package.js` file

2024-12-06 16:03 UTC, zodern commented
Since the package already has a dependency on `zodern:types`, it doesn't need the `addAssets` call. `zodern:types` already ensures the .d.ts files are included when the package is published.

The only reason the other packages need it is because they didn't have a dependency on `zodern:types`. With how zodern:types currently works, doing both can break the types when the package doesn't have a `package-types.json`, since `zodern:types` isn't sure which `.d.ts` file to use.

2024-12-09 03:55 UTC, StorytellerCZ requested changes

2024-12-09 03:55 UTC, StorytellerCZ commented on packages/roles/package.js
Adding via asset, can't we then remove `zodern:types`?

2024-12-09 14:24 UTC, Grubba27 commented
Found the issue, it was missing the export from the file

2024-12-09 14:32 UTC, nachocodoner approved these changes

2024-12-09 14:33 UTC, merged